kubectl apply -f k8s/backend-deployment.yaml
kubectl apply -f k8s/proxy-deployment.yaml
kubectl apply -f k8s/db-deployment.yaml
kubectl apply -f k8s/backend-service.yaml
kubectl apply -f k8s/proxy-service.yaml
kubectl apply -f k8s/db-service.yaml
kubectl apply -f k8s/db-pv.yaml
kubectl apply -f k8s/db-pvc.yaml
kubectl apply -f k8s/db-secret.yaml