apiVersion: v1
kind: Service
metadata:
  name: backend-service
  namespace: webapp
spec:
  selector:
    app: backend
  ports:
  - name: backend-service
    protocol: TCP
    port: 8000
    targetPort: 8000
  type: ClusterIP
