apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-deployment
  namespace: webapp
  labels:
    app: backend-deployment
spec:
  selector:
    matchLabels:
      app: backend
  replicas: 2
  template:
    metadata:
      labels:
        app: backend
    spec:
      volumes:
      - name: db-credentials
        secret: 
          secretName: db-credentials
      containers:
      - name: backend
        image: backend
        imagePullPolicy: Never
        ports:
        - containerPort: 8000
        volumeMounts:
        - name: db-credentials
          mountPath: /run/secrets
          readonly: true


